import { useEffect, useState } from 'react'
import { LoaderCircle, Plus, RefreshCw, Trash2 } from 'lucide-react'
import { adminFetch } from '../auth'

const API = 'https://mazzajoy.uz/api/v1/admin/platform/'
type CatalogData = { regions: any[]; categories: any[]; comfortables: any[]; rules: any[]; currency_rate?: {rate?: string}; banners: any[] }

export function Catalog() {
  const [data,setData]=useState<CatalogData|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState('')
  const load=async()=>{setBusy('load');setError('');try{const r=await adminFetch(`${API}?section=catalog`);const d=await r.json();if(!r.ok)throw Error(d.detail);setData(d)}catch(e){setError(e instanceof Error?e.message:'Xatolik')}finally{setBusy('')}}
  useEffect(()=>{void load()},[])
  const add=async(entity:string)=>{const name=window.prompt('Nomi:');if(!name)return;setBusy(entity);try{const r=await adminFetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'catalog_create',entity,name})});if(!r.ok)throw Error((await r.json()).detail);await load()}catch(e){setError(e instanceof Error?e.message:'Saqlanmadi')}finally{setBusy('')}}
  const remove=async(entity:string,id:number)=>{if(!confirm('O‘chirishni tasdiqlaysizmi?'))return;setBusy(`${entity}${id}`);try{const r=await adminFetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'catalog_delete',entity,id})});if(!r.ok)throw Error((await r.json()).detail);await load()}catch(e){setError(e instanceof Error?e.message:'O‘chirilmadi')}finally{setBusy('')}}
  const updateRate=async()=>{const rate=window.prompt('1 USD uchun so‘m kursi:',data?.currency_rate?.rate||'');if(rate===null||!rate.trim())return;setBusy('rate');try{const r=await adminFetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update_currency_rate',rate})});if(!r.ok)throw Error((await r.json()).detail);await load()}catch(e){setError(e instanceof Error?e.message:'Kurs yangilanmadi')}finally{setBusy('')}}
  const addBanner=async(file:File)=>{setBusy('banner');try{const form=new FormData();form.append('action','create_banner');form.append('image',file);const r=await adminFetch(API,{method:'POST',body:form});if(!r.ok)throw Error((await r.json()).detail);await load()}catch(e){setError(e instanceof Error?e.message:'Banner qo‘shilmadi')}finally{setBusy('')}}
  if(!data)return <section className="panel finance-state"><LoaderCircle className="spin"/> {error||'Katalog yuklanmoqda...'}</section>
  const groups:[string,string,any[]][]=[['Hududlar','region',data.regions],['Kategoriyalar','category',data.categories],['Qulayliklar','comfortable',data.comfortables],['Qoidalar','rule',data.rules]]
  return <section className="panel directory"><div className="panel-head"><div><h2>Platforma sozlamalari</h2><p>Katalog, valyuta kursi va mobil ilovada chiqadigan bannerlarni boshqaring.</p></div><button className="range" onClick={()=>void load()}><RefreshCw size={14}/> Yangilash</button></div>{error&&<p className="directory-notice error">{error}</p>}<div className="catalog-grid">{groups.map(([title,entity,items])=><div className="catalog-card" key={entity}><div><strong>{title}</strong><button onClick={()=>void add(entity)} disabled={!!busy}><Plus size={15}/> Qo‘shish</button></div>{items.length?items.map(item=><p key={item.id}><span>{item.name}</span><button onClick={()=>void remove(entity,item.id)} disabled={!!busy}><Trash2 size={14}/></button></p>):<small>Hozircha yo‘q</small>}</div>)}</div><div className="catalog-grid catalog-extra"><div className="catalog-card"><div><strong>Valyuta kursi</strong><button onClick={()=>void updateRate()} disabled={!!busy}>Yangilash</button></div><p><span>1 USD</span><b>{data.currency_rate?.rate||'Kiritilmagan'} so‘m</b></p></div><div className="catalog-card"><div><strong>Bannerlar</strong><label className="catalog-upload"><Plus size={15}/> Rasm qo‘shish<input type="file" accept="image/*" onChange={event=>{const file=event.target.files?.[0];if(file)void addBanner(file);event.currentTarget.value=''}} disabled={!!busy}/></label></div>{data.banners.length?data.banners.map(item=><p key={item.id}><a href={`https://mazzajoy.uz${item.image}`} target="_blank" rel="noreferrer">Banner #{item.id}</a><button onClick={()=>void remove('banner',item.id)} disabled={!!busy}><Trash2 size={14}/></button></p>):<small>Hozircha banner yo‘q</small>}</div></div></section>
}
