import { useEffect, useState } from 'react'
import { LoaderCircle, Plus, RefreshCw, Trash2 } from 'lucide-react'
import { adminFetch } from '../auth'

const API = 'https://mazzajoy.uz/api/v1/admin/platform/'
type Category = { id:number; name:string; minimum_payment_mode?: 'percent'|'fixed'; minimum_payment_value?: string|number; allows_multiple_rooms?: boolean }
type CatalogData = { regions: any[]; categories: Category[]; comfortables: any[]; rules: any[]; cancellation_policies?: any[]; banners: any[] }

export function Catalog() {
  const [data,setData]=useState<CatalogData|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState('')
  const load=async()=>{setBusy('load');setError('');try{const r=await adminFetch(`${API}?section=catalog`);const d=await r.json();if(!r.ok)throw Error(d.detail);setData(d)}catch(e){setError(e instanceof Error?e.message:'Xatolik')}finally{setBusy('')}}
  useEffect(()=>{void load()},[])
  const add=async(entity:string)=>{const name=window.prompt('Nomi:');if(!name)return;setBusy(entity);try{const r=await adminFetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'catalog_create',entity,name})});if(!r.ok)throw Error((await r.json()).detail);await load()}catch(e){setError(e instanceof Error?e.message:'Saqlanmadi')}finally{setBusy('')}}
  const remove=async(entity:string,id:number)=>{if(!confirm('O‘chirishni tasdiqlaysizmi?'))return;setBusy(`${entity}${id}`);try{const r=await adminFetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'catalog_delete',entity,id})});if(!r.ok)throw Error((await r.json()).detail);await load()}catch(e){setError(e instanceof Error?e.message:'O‘chirilmadi')}finally{setBusy('')}}
  const configureMinimumPayment=async(category:Category)=>{const mode=window.prompt('To‘lov turi: percent yoki fixed',category.minimum_payment_mode||'percent');if(mode===null)return;if(mode!=='percent'&&mode!=='fixed'){setError('Faqat percent yoki fixed tanlang.');return}const value=window.prompt(mode==='percent'?'Bron narxidan foizni kiriting:':'Minimal to‘lov summasini (so‘m) kiriting:',String(category.minimum_payment_value||''));if(value===null||!value.trim())return;setBusy(`payment${category.id}`);try{const r=await adminFetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update_category_payment_rule',category_id:category.id,minimum_payment_mode:mode,minimum_payment_value:value})});if(!r.ok)throw Error((await r.json()).detail);await load()}catch(e){setError(e instanceof Error?e.message:'Minimal to‘lov yangilanmadi')}finally{setBusy('')}}
  const configureRoomPolicy=async(category:Category)=>{const enabled=window.confirm(`${category.name} kategoriyasida alohida bron qilinadigan bir nechta xona bo‘lsinmi?\n\nOK — xona qo‘shish agentda ko‘rinadi.\nBekor qilish — mulk bitta bron qilinadigan obyekt bo‘ladi.`);setBusy(`rooms${category.id}`);try{const r=await adminFetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update_category_room_policy',category_id:category.id,allows_multiple_rooms:enabled})});if(!r.ok)throw Error((await r.json()).detail);await load()}catch(e){setError(e instanceof Error?e.message:'Xona sozlamasi yangilanmadi')}finally{setBusy('')}}
  const addPolicy=async()=>{const title=window.prompt('Siyosat sarlavhasi:');if(!title)return;const description=window.prompt('Tavsif:');if(!description)return;const type=window.prompt('Turi: success, warning yoki danger','warning');if(!type)return;setBusy('policy');try{const r=await adminFetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancellation_policy_create',title,description,type})});if(!r.ok)throw Error((await r.json()).detail);await load()}catch(e){setError(e instanceof Error?e.message:'Siyosat saqlanmadi')}finally{setBusy('')}}
  if(!data)return <section className="panel finance-state"><LoaderCircle className="spin"/> {error||'Katalog yuklanmoqda...'}</section>
  const groups:[string,string,any[]][]=[['Hududlar','region',data.regions],['Kategoriyalar','category',data.categories],['Qulayliklar','comfortable',data.comfortables],['Qoidalar','rule',data.rules]]
  return <section className="panel directory"><div className="panel-head"><div><h2>Platforma sozlamalari</h2><p>Katalog, kategoriya bron to‘lovi va xona turini boshqaring.</p></div><button className="range" onClick={()=>void load()}><RefreshCw size={14}/> Yangilash</button></div>{error&&<p className="directory-notice error">{error}</p>}<div className="catalog-grid">{groups.map(([title,entity,items])=><div className="catalog-card" key={entity}><div><strong>{title}</strong><button onClick={()=>void add(entity)} disabled={!!busy}><Plus size={15}/> Qo‘shish</button></div>{items.length?items.map(item=><p key={item.id}><span>{item.name}</span>{entity==='category'?<><button className="payment-rule" onClick={()=>void configureMinimumPayment(item as Category)} disabled={!!busy}>{(item as Category).minimum_payment_mode==='fixed'?`${(item as Category).minimum_payment_value||0} so‘m`:`${(item as Category).minimum_payment_value||0}%`}</button><button className="payment-rule" onClick={()=>void configureRoomPolicy(item as Category)} disabled={!!busy}>{(item as Category).allows_multiple_rooms?'Ko‘p xona: Ha':'Ko‘p xona: Yo‘q'}</button></>:null}<button onClick={()=>void remove(entity,item.id)} disabled={!!busy}><Trash2 size={14}/></button></p>):<small>Hozircha yo‘q</small>}</div>)}</div><div className="catalog-grid catalog-extra"><div className="catalog-card"><div><strong>Bekor qilish siyosati</strong><button onClick={()=>void addPolicy()} disabled={!!busy}><Plus size={15}/> Qo‘shish</button></div>{(data.cancellation_policies||[]).length?(data.cancellation_policies||[]).map(item=><p key={item.id}><span>{item.title}</span><button onClick={()=>void remove('cancellation_policy',item.id)} disabled={!!busy}><Trash2 size={14}/></button></p>):<small>Hozircha yo‘q</small>}</div><div className="catalog-card"><div><strong>Valyuta</strong></div><p><span>Barcha hisob-kitoblar</span><b>Faqat UZS / so‘m</b></p></div></div></section>
}
